### ISSUE TITLE
terraform init fails due to constraints on aws module

### ISSUE THREAD

**Issue by dylanmtaylor** [hashicorp/learn-terraform-eks#49]
After doing a git checkout, I get this message:

│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/aws:
│ locked provider registry.terraform.io/hashicorp/aws 3.53.0 does not match
│ configured version constraint >= 3.15.0, >= 3.20.0, >= 3.40.0, >= 3.56.0;
│ must use terraform init -upgrade to allow selection of new versions
╵

Constraints in this project might need to be adjusted.

**Comment by evolart** [comment]
Same issue...following the written directions results in the error:

`Could not retrieve the list of available versions for provider hashicorp/aws: locked provider registry.terraform.io/hashicorp/aws 3.63.0 does not match configured version constraint >= 3.15.0, >= 3.20.0, >= 3.64.0; must use terraform init -upgrade to allow selection of new versions`

Running `terraform init -upgrade` does work but the documentation https://learn.hashicorp.com/tutorials/terraform/eks?in=terraform/kubernetes doesn't state to do it.
